blank_issues_enabled: false
contact_links:
  - name: General Question or Help
    url: https://github.com/lalepi/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and discuss with the community
